### ISSUE TITLE
Bridge actor doesn't have "outbox" property

### ISSUE THREAD

**Issue by juanro49** [nanikamado/momostr#7]
The outbox property is required by ActivityPub standard: https://www.w3.org/TR/activitypub/#actor-objects (the collection can be empty).

This causes the problem ‘json parse error: missing field `outbox`’ with some fediverse servers such as mitra. https://codeberg.org/silverpill/mitra

Example https://momostr.pink/users/npub1hgclq59xd44wuulmykzqtfz0elaxvt3y0p8xv5y5f78u95cgjsnshhy0we

**Comment by nanikamado** [comment]
Fixed.
