### ISSUE TITLE
Federation issues with Pleroma

### ISSUE THREAD

**Issue by syobocat** [nanikamado/momostr#9]
Hello. I've just found some issues when I tried to bridge Nostr and Pleroma using momostr:
- I cannot follow momostr users from Pleroma  
  I found a similar issue (with the same error message) reported about FunkWhale (see https://git.pleroma.social/pleroma/pleroma/-/issues/2539 ), but links in the comments [seems temporarily unavailable](https://www.reddit.com/r/Funkwhale/comments/1dlrsqn/funkwhaleaudio_down/).
- I cannot fetch momostr posts from Pleroma
  The errors message on Pleroma is the following, and I guess the problem is that the `url` field on momostr notes is not a String but an Array (sorry if I'm wrong).
```
Jun 25 11:19:35 syo pleroma[83569]: [error] Error while fetching https://momostr.pink/notes/note1lqd6l77tdpmhvx36g45yc6r74q39fa55uccws5dw7ysr9a3mxjqq6ye03g: {:error, {:transmogrifier, {:error, {:validate, {:error, [#Ecto](https://syo.bar/tag/ecto).Changeset<action: :insert, changes: %{actor: "https://momostr.pink/users/npub1a8uawcs9gd3qt2mglat0ltah3vhlk65vpudeva29zfnf806lewrqwpqar9", attributedTo: "https://momostr.pink/users/npub1a8uawcs9gd3qt2mglat0ltah3vhlk65vpudeva29zfnf806lewrqwpqar9", content: "<span>t</span>", context: "https://momostr.pink/notes/note1lqd6l77tdpmhvx36g45yc6r74q39fa55uccws5dw7ysr9a3mxjqq6ye03g", id: "https://momostr.pink/notes/note1lqd6l77tdpmhvx36g45yc6r74q39fa55uccws5dw7ysr9a3mxjqq6ye03g", published: "2024-06-25T02:18:50Z", type: "Note"}, errors: [url: {"is invalid", [type: Pleroma.EctoType.ActivityPub.ObjectValidators.BareUri, validation: :cast]}], data: [#Pleroma](https://syo.bar/tag/pleroma).Web.ActivityPub.ObjectValidators.ArticleNotePageValidator<>, valid?: false>}}}}}
Jun 25 11:19:35 syo pleroma[83569]: [warn] Couldn't fetch "https://momostr.pink/notes/note1lqd6l77tdpmhvx36g45yc6r74q39fa55uccws5dw7ysr9a3mxjqq6ye03g", error: nil
```
- Custom Emoji Reactions from Nostr just become `Like`s  
  While custom emoji reactions are perfectly bridged between Nostr and Misskey, I cannot see them on Pleroma and they just turn into `Like`s.  
  I've heard that Misskey and Pleroma implement Emoji Recations differently (Misskey overloads the `Like` activity while Pleroma uses the `EmojiReact` activity), so that could be the reason.

**Comment by nanikamado** [comment]
> I cannot fetch momostr posts from Pleroma

Fixed by ebad04e6a276066784fd1fffedfc68738de2c390.
